
OPCAO_INICIAR_ATENDIMENTO = 1
OPCAO_FECHAR_CAIXA = 2
OPCAO_INSERIR_ITEM = 1
OPCAO_FINALIZAR_ATENDIMENTO = 2
PRODUTO_IDX_ID = 0
PRODUTO_IDX_NOME = 1
PRODUTO_IDX_ESTOQUE = 2
PRODUTO_IDX_PRECO = 3
ITEM_IDX_ID = 0
ITEM_IDX_NOME = 1
ITEM_IDX_QTD = 2
ITEM_IDX_PRECO_UN = 3
ITEM_IDX_PRECO_TOT = 4